### ISSUE TITLE
Multi-line union syntax not accepted

### ISSUE THREAD

**Issue by Tatsh** [jecki/ts2python#10]
I get

```
1:1: Error (1000): Malformed syntax-tree! Possibly caused by a parsing error.
1:13: Error (1010): 'declarations_block' expected by parser 'interface', but »{\n  k:\n   ...« found instead!
6:2: Error (1040): Parser "_root" stopped before end, at: »\n« Terminating parser.
```

with the following:

```
interface I {
  k: 
    | 1
    | 2
    | 3;
}
```

`1 | 2 | 3` works fine.

Formatters will convert to this syntax to cut lines to fit in the maximum length, but it's also simply valid syntax so it should be accepted.

**Comment by jecki** [comment]
Thanks for telling me! I have fixed it in the development branch and I added the example as a test-case  to tests/08_test_interfaces.ini.
It compiles to:     
```
class I(TypedDict):
        k: Literal[1, 2, 3]
```

**Comment by Tatsh** [comment]
Ok I will use the latest HEAD for now in projects.
