### ISSUE TITLE
bug ModuleNotFoundError: No module named 'ts2pythonParser'

### ISSUE THREAD

**Issue by wanghaisheng** [jecki/ts2python#11]
dubo@LAPTOP-I2R9VG58 MINGW64 /d/Download/audio-visual/saas/tiktoka/youtube-uploader-ts2py (py)
$ pip install ts2python
WARNING: Ignoring invalid distribution -laywright (d:\programs\anaconda\envs\py3.8\lib\site-packages)
WARNING: Ignoring invalid distribution -laywright (d:\programs\anaconda\envs\py3.8\lib\site-packages)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: ts2python in d:\programs\anaconda\envs\py3.8\lib\site-packages (0.6.8)
Requirement already satisfied: typing_extensions<5.0,>=4.0 in d:\programs\anaconda\envs\py3.8\lib\site-packages (from ts2python) (4.2.0)
Requirement already satisfied: DHParser<1.5,>=1.4 in d:\programs\anaconda\envs\py3.8\lib\site-packages (from ts2python) (1.4.2)
Requirement already satisfied: regex in d:\programs\anaconda\envs\py3.8\lib\site-packages (from DHParser<1.5,>=1.4->ts2python) (2023.5.5)
WARNING: Ignoring invalid distribution -laywright (d:\programs\anaconda\envs\py3.8\lib\site-packages)
WARNING: Ignoring invalid distribution -laywright (d:\programs\anaconda\envs\py3.8\lib\site-packages)
WARNING: Ignoring invalid distribution -laywright (d:\programs\anaconda\envs\py3.8\lib\site-packages)
WARNING: Ignoring invalid distribution -laywright (d:\programs\anaconda\envs\py3.8\lib\site-packages)

dubo@LAPTOP-I2R9VG58 MINGW64 /d/Download/audio-visual/saas/tiktoka/youtube-uploader-ts2py (py)
$ ts2python src/upload.ts 
Traceback (most recent call last):
  File "D:/Programs/anaconda/envs/py3.8/Scripts/ts2python", line 3, in <module>
    from ts2pythonParser import main
ModuleNotFoundError: No module named 'ts2pythonParser'

**Comment by jecki** [comment]
Thanks for your report! Unfortunately, I was not able to reproduce the bug. (I tried this with a fresh virtual environment.) So I can only guess: In case you have several version of python installed on your system, say one that has been installed with anaconda and another one with the regular Python installer that ts2python has been installed in the site-packages of one of these versions which, however, is not the version of the python-interpreter that is found on the regular system path... But I am not sure about that.

A possible workaround would be to create and activate a virtual environment and then install ts2python into that virtual environment and run it from there. About venvs, see: https://www.freecodecamp.org/news/how-to-setup-virtual-environments-in-python/
