### ISSUE TITLE
Upgrade to DHParser-1.1?

### ISSUE THREAD

**Issue by alonbl** [jecki/ts2python#3]
Hello,

The wheel does not have restriction on the DHParser version, the `DHParser` which is pulled now is 1.1 while it is backward incompatible.

Short term solution is to apply a conditional version for `DHParser` to be 1.0.x.

Please consider to upgrade to 1.1 as well, and also solve:

```
DeprecationWarning: Property "DHParser.nodetree.Node.tag_name" is deprecated. Use "Node.name" instead!
```

Thanks!

**Comment by jecki** [comment]
This has been solved, meanwhile. Thanks for reporting!
