### ISSUE TITLE
Ignore `import` statements?

### ISSUE THREAD

**Issue by alonbl** [jecki/ts2python#4]
Hi,

When a module has import statements, for example:

```
import {CommentRange} from './core';
```

I get the following error:

```
1:1: Error (1000): Malformed syntax-tree! Possibly caused by a parsing error.
1:8: Error (1040): Parser "declaration->`:`" did not match: »{CommentRange} from  ...«
```

Removing the imports enables me to produce something decent and usable.
Short term solution: maybe ignore modules with warnings?
Long term solution: process?

Reference script[1]

Thanks!
Alon

[1] https://gerrit.googlesource.com/gerrit/+/master/polygerrit-ui/app/api/checks.ts

**Comment by jecki** [comment]
Thanks for the suggestions. I do not think it would be too hard to add at least a simplified version of imports, where the complete file is imported. So I am planning to do this in the not too distant future.

**Comment by geyang** [comment]
just want to bump this up -- running into the same problem.

**Comment by jecki** [comment]
The latest version in the git repository now reads and silently ignores Typescript import statements.
You will have to pull the latest DHParser version from git, before it works. 
I plan update DHParser and ts2python in PyPI soon.
