### ISSUE TITLE
Mypy/Pylance do not accept non-type annotations inside TypedDict

### ISSUE THREAD

**Issue by Tatsh** [jecki/ts2python#9]
Pylance: `TypedDict classes can contain only type annotations`

Mypy:

```
error: Invalid statement in TypedDict definition; expected "field_name: field_type"  [misc]
error: Name "Post_metadata_0" is not defined  [name-defined]
```

Can you make the output go outside of the class with a prefix?

Instead of:

```python
class Posts(TypedDict):
    class Links_0(TypedDict):
        next: str | None

    data: Sequence[PostsDataDict]
    links: Links_0
```

do:

```python
class _Posts_Links_0(TypedDict):
    next: str | None


class Posts(TypedDict):
    data: Sequence[PostsDataDict]
    links: Posts_Links_0
```

I am adding the `_` prefix to it so it's marked by convention as private.

**Comment by jecki** [comment]
Thanks for pointing this out to me. I agree this should be fixed. It involve a bit of work, though and will thus take me some time.

**Comment by jecki** [comment]
It's been a while... Upcoming Version 0.7 which is now already in git main and will soon be published to PyPI now supports this with the command line switch "-a toplevel"

**Comment by Tatsh** [comment]
When does 0.7 go into PyPI?

**Comment by jecki** [comment]
Oh, it has been uploaded right now...

**Comment by Tatsh** [comment]
I tried adding with Poetry and definitely have it installed but I got this error:

```
(virtualenv) $ ts2python x.ts
Could not check whether grammar requires recompiling, because grammar was not found at: $VIRTUALENV/lib/python3.10/site-packages/ts2python.ebnf
```

**Comment by Tatsh** [comment]
Yes you just need to include `ts2python.ebnf` in `[tool.poetry].include`:

```toml
[tool.poetry]
include = ["ts2python.ebnf"]
```

I recommend verifying that the tarball has the file before publishing to PyPI.

Also you really should not be including these generically named directories: https://github.com/jecki/ts2python/blob/main/pyproject.toml#L43C1-L46C43 They may conflict with other packages but are also not necessary for the package to work.

**Comment by jecki** [comment]
Thank you very much for pointing this out to me. This all should be remedied now, with version 0.7.3. The error message complaining about a missing .ebnf-file should not keep the program from continuing.

**Comment by Tatsh** [comment]
No problem. This is a great tool and I have a few more things to go over but I'll look for/open new issues.
